[main]
font=BlexMono Nerd Font:size=14
pad=0x0

[scrollback]
lines=1500
multiplier=10.0

[colors-dark]
alpha=0.75

foreground=ebdbb2
background=272727

selection-foreground=655b53
selection-background=ebdbb2

cursor=928374 ebdbb2

regular0=272727
regular1=cc231c
regular2=989719
regular3=d79920
regular4=448488
regular5=b16185
regular6=689d69
regular7=a89983

bright0=928373
bright1=fb4833
bright2=b8ba25
bright3=fabc2e
bright4=83a597
bright5=d3859a
bright6=8ec07b
bright7=ebdbb2

[url]
osc8-underline=always
