-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — top-level key 'splash = false' has no enclosing section

-- TODO: manual review — unknown section 'wallpaper {' on line 3
