--###################
--## MY PROGRAMS  ###
--###################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local terminal = "kitty"
local fileManager = "dolphin"
local menu = "hyprlauncher"
local browser = "zen-browser"

--##############
--## SOURCES ###
--##############

-- Source: $HOME/.config/hypr/taylor/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_HOME._config.hypr.taylor.monitors")
-- Source: $HOME/.config/hypr/taylor/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_HOME._config.hypr.taylor.autostart")
-- Source: $HOME/.config/hypr/taylor/environment.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_HOME._config.hypr.taylor.environment")
-- Source: $HOME/.config/hypr/taylor/visuals.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_HOME._config.hypr.taylor.visuals")
-- Source: $HOME/.config/hypr/taylor/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_HOME._config.hypr.taylor.input")
-- Source: $HOME/.config/hypr/taylor/keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_HOME._config.hypr.taylor.keybinds")
-- Source: $HOME/.config/hypr/taylor/rules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_HOME._config.hypr.taylor.rules")
