-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'listener {' on line 7

-- TODO: manual review — unknown section 'listener {' on line 14

-- TODO: manual review — unknown section 'listener {' on line 20

-- TODO: manual review — unknown section 'listener {' on line 25

-- TODO: manual review — unknown section 'listener {' on line 31
hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock", -- avoid starting multiple hyprlock instances.
        before_sleep_cmd = "loginctl lock-session", -- lock before suspend.
        after_sleep_cmd = "hyprctl dispatch dpms on", -- to avoid having to press a key twice to turn on the display.
    },
    -- turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
})

