-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'background {' on line 1

-- TODO: manual review — unknown section 'label {' on line 12

-- TODO: manual review — unknown section 'shape {' on line 24

-- TODO: manual review — unknown section 'input-field {' on line 35
hl.config({
    general = {
        hide_cursor = false,
        grace = 0,
        no_fade_in = false,
    },
})

