####################
### MY PROGRAMS  ###
####################

$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher
$browser = zen-browser

###############
### SOURCES ###
###############

source = $HOME/.config/hypr/taylor/monitors.conf
source = $HOME/.config/hypr/taylor/autostart.conf
source = $HOME/.config/hypr/taylor/environment.conf
source = $HOME/.config/hypr/taylor/visuals.conf
source = $HOME/.config/hypr/taylor/input.conf
source = $HOME/.config/hypr/taylor/keybinds.conf
source = $HOME/.config/hypr/taylor/rules.conf
