-- hyprtoolkit — shared theming for all hyprtoolkit apps (hyprlauncher, ...)
-- Swap the line below to change theme. See ./palettes/ for options.
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/palettes/gruvbox-dark.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("palettes.gruvbox-dark")

-- TODO: manual review — top-level key 'rounding_large = 10' has no enclosing section
-- TODO: manual review — top-level key 'rounding_small = 5' has no enclosing section

-- TODO: manual review — top-level key 'h1_size = 19' has no enclosing section
-- TODO: manual review — top-level key 'h2_size = 15' has no enclosing section
-- TODO: manual review — top-level key 'h3_size = 13' has no enclosing section
-- TODO: manual review — top-level key 'font_size = 12' has no enclosing section
-- TODO: manual review — top-level key 'small_font_size = 11' has no enclosing section

-- TODO: manual review — top-level key 'font_family = BlexMono Nerd Font' has no enclosing section
-- TODO: manual review — top-level key 'font_family_monospace = BlexMono Nerd Font' has no enclosing section

-- TODO: manual review — top-level key 'icon_theme = ' has no enclosing section
