#################
### AUTOSTART ###
#################

exec-once = source .zshrc
exec-once = hyprpaper
exec-once = swyanc
exec-once = hypridle
exec-once = udiskie &
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = /home/taylor/dotfiles/scripts/filen-automount.sh
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = pika-backup-monitor
exec-once = protonmail-bridge --no-window
exec-once = gnome-keyring-daemon --start --components=secrets


####################
### STARTUP APPS ###
####################

exec-once = [workspace 1 silent] $terminal
exec-once = [workspace 2 silent] $browser
exec-once = [workspace 3 silent] signal-desktop
exec-once = [workspace 3 silent] caprine
exec-once = [workspace 4 silent] $fileManager
exec-once = [workspace 8 silent] bitwarden-desktop
# exec-once = [workspace 9 silent] pika-backup
exec-once = [workspace 10 silent] thunderbird
