--################
--## AUTOSTART ###
--################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

--###################
--## STARTUP APPS ###
--###################

-- exec-once = [workspace 8 silent] bitwarden-desktop
-- exec-once = [workspace 9 silent] pika-backup
-- exec-once = [workspace 10 silent] thunderbird

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("dunst")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("waybar")
    hl.exec_cmd("udiskie --tray")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 24")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE")
    hl.exec_cmd("systemctl --user start filen-automount.service")
    hl.exec_cmd("pika-backup-monitor")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("blueman-tray")
    hl.exec_cmd("$terminal", { workspace = "1 silent" })
    hl.exec_cmd("$browser", { workspace = "2 silent" })
    hl.exec_cmd("signal-desktop", { workspace = "3 silent" })
    hl.exec_cmd("$fileManager", { workspace = "4 silent" })
end)

