#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = HYPRSHOT_DIR, $HOME/Pictures/Screenshots
env = ELECTRON_OZONE_PLATFORM_HINT=auto
env = GNOME_KEYRING_CONTROL,/run/user/1000/keyring
