--############
--## INPUT ###
--############

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.device({
    name = "kinesis-corporation-adv360-pro-keyboard",
    kb_options = "",
})

hl.device({
    name = "moergo-glove80-left-keyboard",
    kb_options = "",
})

hl.device({
    name = "logitech-usb-receiver-mouse",
    sensitivity = 0.0,
})

hl.device({
    name = "razer-razer-abyssus-essential-1",
    sensitivity = -1.0,
})

hl.device({
    name = "elan0678:00-04f3:3195-touchpad",
    sensitivity = 0.0,
})

hl.device({
    name = "logitech-usb-receiver-mouse",
    sensitivity = -1.0,
})

hl.device({
    name = "kbdfans-maja_soldered",
    kb_options = "caps:none",
})

hl.device({
    name = "kbdfans-maja_soldered-system-control",
    kb_options = "caps:none",
})

hl.device({
    name = "kbdfans-maja_soldered-consumer-control",
    kb_options = "caps:none",
})

hl.device({
    name = "kbdfans-maja_soldered-keyboard",
    kb_options = "caps:none",
})

hl.config({
    input = {
        kb_layout = "dk",
        kb_variant = "",
        kb_model = "",
        kb_options = "caps:swapescape",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = -1.0,
        force_no_accel = false,
        touchpad = {
            natural_scroll = true,
        },
    },
    --##############
    --## DEVICES ###
    --##############
})

