################
### MONITORS ###
################

monitor = eDP-1,preferred,0x0,1.5
monitor = , preferred, auto, 1, mirror, eDP-1

# monitor = DP-1, preferred, 0x0, 1.25
# monitor = HDMI-A-1, disable
# monitor = HDMI-A-1, preferred, 0x0, 1, mirror, DP-1

# Hotkeys to switch between monitors
# bind = SUPER SHIFT, Y, exec, hyprctl keyword monitor "eDP-1, 1920x1200, 0x0, 1.2" && hyprctl keyword monitor "DP-8, disable"
bind = SUPER SHIFT, Y, exec, hyprctl keyword monitor "eDP-1, 1920x1200, 0x0, 1" && hyprctl keyword monitor "DP-8, disable"
bind = SUPER SHIFT, U, exec, hyprctl keyword monitor "DP-8, 3840x2160, auto, 2" && hyprctl keyword monitor "eDP-1, disable"
