##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    name = iwgtk-floating
    match:class = ^(org\.twosheds\.iwgtk)$

    float = true
    size = 400 600
    move = 1545 40
}

windowrule {
    name = blueman-floating
    match:class = ^(blueman-manager)$

    float = true
    size = 400 600
    move = 1545 40
}

xwayland {
    force_zero_scaling = true
}

windowrule {
    name = center-open-file
    match:title = ^(Open File)$
    center = true
}

windowrule {
    name = center-save-as
    match:title = ^(Save As)$
    center = true
}

windowrule {
    name = center-open
    match:title = ^(Open)$
    center = true
}

windowrule {
    name = center-portal
    match:class = ^(xdg-desktop-portal-gtk)$
    center = true
}

windowrule {
    name = center-fdo-portal
    match:class = ^(org\.freedesktop\.impl\.portal)$
    center = true
}
