--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    name = "iwgtk-floating",
    match = {
        class = "^(org\\.twosheds\\.iwgtk)$",
    },
    float = true,
    size = "400 600",
    move = "1545 40",
})

hl.window_rule({
    name = "blueman-floating",
    match = {
        class = "^(blueman-manager)$",
    },
    float = true,
    size = "400 600",
    move = "1545 40",
})

hl.window_rule({
    name = "center-open-file",
    match = {
        title = "^(Open File)$",
    },
    center = true,
})

hl.window_rule({
    name = "center-save-as",
    match = {
        title = "^(Save As)$",
    },
    center = true,
})

hl.window_rule({
    name = "center-open",
    match = {
        title = "^(Open)$",
    },
    center = true,
})

hl.window_rule({
    name = "center-portal",
    match = {
        class = "^(xdg-desktop-portal-gtk)$",
    },
    center = true,
})

hl.window_rule({
    name = "center-fdo-portal",
    match = {
        class = "^(org\\.freedesktop\\.impl\\.portal)$",
    },
    center = true,
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

