--####################
--## LOOK AND FEEL ###
--####################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    general = {
        gaps_in = 2,
        gaps_out = 2,
        border_size = 2,
        col = {
            active_border = "rgba(a89984ff)",
            inactive_border = "rgba(282828ff)",
        },
        resize_on_border = true,
        allow_tearing = false,
        layout = "dwindle",
    },
    decoration = {
        rounding = 0,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = false,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = true,
            size = 12,
            passes = 4,
            ignore_opacity = false,
            new_optimizations = true,
            xray = true,
        },
    },
    animations = {
        enabled = false,
    },
    master = {
        new_status = "master",
    },
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
    },
})

