-- gruvbox dark — aligned with ~/.config/hypr/taylor/visuals.conf
-- active border  rgba(a89984ff)  -> accent
-- inactive bord. rgba(282828ff)  -> background
-- shadow         rgba(1a1a1aee)  -> base

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — top-level key 'background = 0xff282828' has no enclosing section
-- TODO: manual review — top-level key 'base = 0xff1a1a1a' has no enclosing section
-- TODO: manual review — top-level key 'alternate_base = 0xff3c3836' has no enclosing section
-- TODO: manual review — top-level key 'text = 0xffebdbb2' has no enclosing section
-- TODO: manual review — top-level key 'bright_text = 0xfffbf1c7' has no enclosing section
-- TODO: manual review — top-level key 'link_text = 0xff83a598' has no enclosing section
-- TODO: manual review — top-level key 'accent = 0xffa89984' has no enclosing section
-- TODO: manual review — top-level key 'accent_secondary = 0xffd79921' has no enclosing section
